import { defineConfig } from 'astro/config';
import vercel from '@astrojs/vercel/serverless';

// Hybrid output: pages are static by default, but src/pages/go/[slug].ts
// opts in to SSR via `export const prerender = false` so each click is
// recorded server-side and redirected dynamically.
//
// Sitemap intentionally generated by src/pages/sitemap.xml.ts rather than
// the @astrojs/sitemap integration — the integration crashes on hybrid +
// vercel adapter combos (reads result.pages = undefined). The hand-rolled
// version reads pages.json directly and is trivial to maintain.
export default defineConfig({
  site: 'https://mens-leather-wallet-pending.example',
  output: 'hybrid',
  adapter: vercel(),
  trailingSlash: 'always',
});
